import React, { useState, useEffect } from 'react';

const MOODS = [
  { id: 'romantic', icon: '🌹', label: 'Romantic' },
  { id: 'sad', icon: '💧', label: 'Sad / Nostalgic' },
  { id: 'dance', icon: '💃', label: 'Dance / Cabaret' },
  { id: 'ghazal', icon: '🌙', label: 'Ghazal' },
  { id: 'devotional', icon: '🪔', label: 'Devotional' },
];

export default function App() {
  const [selectedMood, setSelectedMood] = useState(null);
  const [playlist, setPlaylist] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [apiKey, setApiKey] = useState('');

  const handleGenerate = async () => {
    if (!selectedMood) return;
    if (!apiKey) {
      setError('Please provide a Gemini API Key to generate the tribute.');
      return;
    }

    setLoading(true);
    setError(null);
    setPlaylist(null);

    const moodObj = MOODS.find(m => m.id === selectedMood);

    try {
      const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          systemInstruction: {
            parts: [{ text: "You are a Bollywood music historian and tribute curator. Asha Bhosle, the legendary Indian playback singer (1933–2026), passed away today. Generate a Top 10 Asha Bhosle songs playlist for the mood provided. Respond ONLY in JSON format with an array of objects. Do not include markdown formatting like ```json or any other text." }]
          },
          contents: [{
            role: "user",
            parts: [{ text: `Generate Top 10 Asha Bhosle songs for mood: ${moodObj.label}. For each song return exactly this structure: { "title": "...", "movie": "...", "year": "...", "composer": "...", "short_story": "...", "why_it_matters": "...", "youtube_search_query": "..." }` }]
          }],
          generationConfig: {
            responseMimeType: "application/json",
          }
        })
      });

      if (!response.ok) {
        const errData = await response.json();
        throw new Error(errData.error?.message || 'Failed to fetch from Gemini API');
      }

      const data = await response.json();
      let textContent = data.candidates[0].content.parts[0].text.trim();
      
      // Cleanup any markdown if the model hallucinated it
      if (textContent.startsWith('```json')) {
        textContent = textContent.replace(/^```json/, '').replace(/```$/, '').trim();
      } else if (textContent.startsWith('```')) {
        textContent = textContent.replace(/^```/, '').replace(/```$/, '').trim();
      }

      const parsedPlaylist = JSON.parse(textContent);
      
      // Add slight delay for animation effect
      setTimeout(() => {
        setPlaylist(parsedPlaylist);
        setLoading(false);
      }, 1000);
      
    } catch (err) {
      setError(err.message);
      setLoading(false);
    }
  };

  const handleShare = async () => {
    if (!playlist || !selectedMood) return;
    const moodObj = MOODS.find(m => m.id === selectedMood);
    
    let shareText = `My Asha Forever ${moodObj.label} Playlist 🙏🎵\n\n`;
    playlist.forEach((song, idx) => {
      shareText += `${idx + 1}. ${song.title} – ${song.movie}\n`;
    });
    shareText += `\nGenerated by AshaForever.app in memory of the Queen of Bollywood\n#AshaBhosle #AshaForever #RIP`;

    try {
      await navigator.clipboard.writeText(shareText);
      alert('Copied to clipboard! Ready to share.');
    } catch (err) {
      console.error('Failed to copy', err);
    }
  };

  const openTweet = () => {
    if (!playlist || !selectedMood) return;
    const moodObj = MOODS.find(m => m.id === selectedMood);
    let shareText = `My Asha Forever ${moodObj.label} Playlist 🙏🎵\n\n`;
    
    // Make tweet shorter if needed, just include top 3 maybe, or maybe it fits
    const top3 = playlist.slice(0, 3).map((song, idx) => `${idx + 1}. ${song.title}`).join('\n');
    shareText += top3 + `\n...\n\nGenerated by AshaForever in memory of the Queen of Bollywood 🙏\n#AshaBhosle #AshaForever #RIP`;
    
    const url = `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}`;
    window.open(url, '_blank');
  };

  return (
    <div className="min-h-screen relative overflow-hidden flex flex-col items-center pb-20">
      <div className="noise-overlay"></div>
      
      {/* Background Glow */}
      <div 
        className="absolute top-0 left-1/2 -translate-x-1/2 w-[600px] h-[400px] rounded-full pointer-events-none opacity-20 blur-[120px]"
        style={{ background: 'radial-gradient(circle, #C9A84C 0%, rgba(10,10,10,0) 70%)' }}
      ></div>

      <div className="relative z-10 w-full max-w-3xl px-6 pt-16 flex flex-col items-center text-center">
        
        {/* Header */}
        <h1 
          className="text-5xl md:text-7xl font-bold mb-4 font-playfair tracking-tight"
          style={{ 
            color: '#C9A84C',
            textShadow: '0 0 20px rgba(201, 168, 76, 0.4)',
            animation: 'shimmer 3s infinite alternate'
          }}
        >
          🎵 Asha Forever
        </h1>
        <p className="text-xl md:text-2xl text-gray-300 font-light max-w-xl mx-auto italic mb-12">
          "A voice that shaped generations. 1933–2026. 🙏"
        </p>

        {/* API Key Input */}
        {!playlist && !loading && (
          <div className="w-full max-w-md mb-10 overflow-hidden rounded-xl border border-[#C9A84C]/30 bg-black/50 backdrop-blur-sm p-4 text-left transition-all hover:border-[#C9A84C]/60">
            <label className="block text-xs uppercase tracking-widest text-[#C9A84C] mb-2 font-bold">API Key Required</label>
            <p className="text-xs text-gray-400 mb-3">Your Gemini API key is required to generate the tribute. It is not saved.</p>
            <input 
              type="password" 
              placeholder="AIzaSy..." 
              value={apiKey}
              onChange={(e) => setApiKey(e.target.value)}
              className="w-full bg-[#1a1a1a] border border-gray-800 rounded-lg px-4 py-3 text-white focus:outline-none focus:border-[#C47B7B] text-sm"
            />
          </div>
        )}

        {/* Mood Selector UI */}
        {!playlist && !loading && (
          <div className="w-full animate-fade-in-up" style={{ animationDelay: '0.2s', animationFillMode: 'both' }}>
            <h3 className="text-sm uppercase tracking-widest text-gray-400 mb-6">Select a Tribute Mood</h3>
            
            <div className="flex flex-wrap justify-center gap-4 mb-10">
              {MOODS.map(mood => {
                const isSelected = selectedMood === mood.id;
                return (
                  <button
                    key={mood.id}
                    onClick={() => setSelectedMood(mood.id)}
                    className="flex flex-col md:flex-row items-center gap-2 px-6 py-4 rounded-xl border transition-all duration-300 transform outline-none"
                    style={{
                      borderColor: isSelected ? '#C9A84C' : '#333',
                      backgroundColor: isSelected ? 'rgba(201, 168, 76, 0.1)' : 'rgba(255,255,255,0.03)',
                      boxShadow: isSelected ? '0 0 20px rgba(201, 168, 76, 0.2)' : 'none',
                      transform: isSelected ? 'scale(1.05)' : 'scale(1)'
                    }}
                  >
                    <span className="text-2xl">{mood.icon}</span>
                    <span className="font-medium text-sm md:text-base whitespace-nowrap" style={{ color: isSelected ? '#C9A84C' : '#ccc' }}>
                      {mood.label}
                    </span>
                  </button>
                );
              })}
            </div>

            {selectedMood && (
              <button
                onClick={handleGenerate}
                className="group relative inline-flex items-center justify-center px-8 py-4 font-bold text-black rounded-full overflow-hidden transition-all hover:scale-105"
                style={{ background: 'linear-gradient(135deg, #C9A84C 0%, #C47B7B 100%)' }}
              >
                <div className="absolute inset-0 bg-white/20 translate-y-full group-hover:translate-y-0 transition-transform duration-300"></div>
                <span className="relative flex items-center gap-2">
                  Generate My Playlist ✨
                </span>
              </button>
            )}

            {error && (
              <div className="mt-6 p-4 rounded-lg bg-red-900/40 border border-red-500/50 text-red-200 text-sm max-w-lg mx-auto">
                <p className="mb-2 font-bold">Generation Failed</p>
                <p className="font-mono text-xs break-words">{error}</p>
                <button onClick={() => setError(null)} className="mt-3 text-[#C9A84C] underline text-xs">Try Again</button>
              </div>
            )}
          </div>
        )}

        {/* Loading State */}
        {loading && (
          <div className="fixed inset-0 z-50 flex flex-col items-center justify-center bg-[#0a0a0a]/90 backdrop-blur-md">
            <div className="relative w-32 h-32 mb-8" style={{ animation: 'shimmer 2s infinite alternate' }}>
              <div className="absolute inset-0 rounded-full border-4 border-[#333]"></div>
              <div className="absolute inset-1 rounded-full border-4 border-dashed border-[#C9A84C] animate-spin-slow"></div>
              <div className="absolute inset-0 flex items-center justify-center text-4xl">🎵</div>
            </div>
            <h2 className="text-2xl font-playfair text-[#C9A84C] animate-pulse">
              Curating your tribute playlist...
            </h2>
          </div>
        )}

        {/* Playlist Results */}
        {playlist && !loading && (
          <div className="w-full text-left animate-fade-in-up mt-8">
            <div className="flex justify-between items-end border-b border-[#333] pb-4 mb-8">
              <div>
                <h2 className="text-3xl font-playfair text-[#C9A84C]">
                  {MOODS.find(m => m.id === selectedMood)?.label} Tribute
                </h2>
                <p className="text-sm text-gray-400 mt-2">10 timeless tracks carefully curated for you.</p>
              </div>
              <button 
                onClick={() => setPlaylist(null)}
                className="text-xs text-gray-500 hover:text-white transition-colors"
              >
                ← Start Over
              </button>
            </div>

            <div className="flex flex-col gap-6 w-full">
              {playlist.map((song, index) => (
                <div 
                  key={index} 
                  className="group flex flex-col md:flex-row gap-6 p-6 rounded-2xl bg-[#111] border border-gray-800 transition-all duration-500 hover:-translate-y-1"
                  style={{
                    animationFillMode: 'both',
                    animation: `fadeInUp 0.6s ease-out ${index * 0.15}s`
                  }}
                  onMouseEnter={(e) => e.currentTarget.style.borderLeft = '4px solid #C9A84C'}
                  onMouseLeave={(e) => e.currentTarget.style.borderLeft = '1px solid #1f2937'}
                >
                  <div className="text-5xl font-playfair font-black text-[#C9A84C] opacity-20 group-hover:opacity-100 transition-opacity flex-shrink-0 pt-2">
                    {String(index + 1).padStart(2, '0')}
                  </div>
                  
                  <div className="flex-grow">
                    <div className="flex flex-wrap items-baseline gap-3 mb-2">
                      <h3 className="text-2xl font-playfair text-white">{song.title}</h3>
                      <span className="text-sm text-gray-500">{song.movie} ({song.year})</span>
                    </div>
                    
                    <div className="inline-block px-3 py-1 rounded-full bg-[#1a1a1a] border border-[#333] text-xs text-gray-300 mb-4">
                      Composer: {song.composer}
                    </div>

                    <p className="text-gray-400 italic text-sm mb-4 leading-relaxed">
                      "{song.short_story}"
                    </p>
                    
                    <div className="flex items-start gap-2 bg-[#C9A84C]/5 px-4 py-3 rounded-lg border border-[#C9A84C]/20 mb-6">
                      <span className="text-sm mt-0.5" style={{ color: '#C9A84C' }}>💛</span>
                      <p className="text-sm font-medium" style={{ color: '#C9A84C' }}>
                        {song.why_it_matters}
                      </p>
                    </div>

                    <a
                      href={`https://www.youtube.com/results?search_query=${encodeURIComponent(song.youtube_search_query)}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg bg-[#cc0000]/10 text-red-400 border border-red-900/50 hover:bg-[#cc0000]/20 hover:text-red-300 transition-colors text-sm font-bold"
                    >
                      ▶ Listen on YouTube
                    </a>
                  </div>
                </div>
              ))}
            </div>

            {/* Share Card Feature */}
            <div className="mt-16 mb-20 p-8 rounded-2xl border border-[#C47B7B]/30 bg-gradient-to-br from-[#111] to-[#1a1a1a] text-center">
              <h3 className="text-2xl font-playfair text-[#C47B7B] mb-4">Keep Her Memory Alive</h3>
              <p className="text-sm text-gray-400 mb-8 max-w-lg mx-auto">
                Music outlives us all. By sharing these timeless classics, you help introduce the Queen of Bollywood to a new generation.
              </p>
              
              <div className="flex flex-wrap justify-center gap-4">
                <button
                  onClick={handleShare}
                  className="px-6 py-3 rounded-full border border-[#C9A84C] text-[#C9A84C] hover:bg-[#C9A84C] hover:text-black transition-colors font-medium text-sm inline-flex flex-row items-center gap-2"
                >
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg>
                  Copy Playlist
                </button>
                <button
                  onClick={openTweet}
                  className="px-6 py-3 rounded-full bg-[#1DA1F2] text-white hover:bg-[#1a8cd8] transition-colors font-medium text-sm inline-flex flex-row items-center gap-2"
                >
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="currentColor"><path d="M23.953 4.57a10 10 0 01-2.825.775 4.958 4.958 0 002.163-2.723c-.951.555-2.005.959-3.127 1.184a4.92 4.92 0 00-8.384 4.482C7.69 8.095 4.067 6.13 1.64 3.162a4.822 4.822 0 00-.666 2.475c0 1.71.87 3.213 2.188 4.096a4.904 4.904 0 01-2.228-.616v.06a4.923 4.923 0 003.946 4.827 4.996 4.996 0 01-2.212.085 4.936 4.936 0 004.604 3.417 9.867 9.867 0 01-6.102 2.105c-.39 0-.779-.023-1.17-.067a13.995 13.995 0 007.557 2.209c9.053 0 13.998-7.496 13.998-13.985 0-.21 0-.42-.015-.63A9.935 9.935 0 0024 4.59z"/></svg>
                  Share on X
                </button>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Footer */}
      <footer className="w-full py-8 mt-auto text-center border-t border-gray-900 z-10 relative">
        <p className="text-gray-400 text-sm mb-2 font-medium">
          Built as a tribute to Asha Bhosle ji (1933–2026). Her voice will live forever. 🙏
        </p>
        <p className="text-gray-600 text-xs">
          Powered by Google Gemini
        </p>
      </footer>

      {/* Inline Keyframes */}
      <style dangerouslySetInnerHTML={{__html: `
        @keyframes shimmer {
          0% { filter: brightness(1) drop-shadow(0 0 10px rgba(201, 168, 76, 0.2)); }
          100% { filter: brightness(1.2) drop-shadow(0 0 25px rgba(201, 168, 76, 0.6)); }
        }
        @keyframes fadeInUp {
          from { opacity: 0; transform: translateY(30px); }
          to { opacity: 1; transform: translateY(0); }
        }
        @keyframes spin-slow {
          from { transform: rotate(0deg); }
          to { transform: rotate(360deg); }
        }
        .animate-fade-in-up {
          animation: fadeInUp 0.8s ease-out;
        }
        .animate-spin-slow {
          animation: spin-slow 8s linear infinite;
        }
      `}} />
    </div>
  );
}
